name: Check requirements.txt
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check requirements.txt
        uses: ekvanox/pipreqs-action@master

        with:
          PROJECT_PATH: ./
          REQUIREMENT_PATH: ./{{ github.workspace }}
          COMMIT_MESSAGE: "Updated requirements file"
      - uses: actions/upload-artifact@v4
        with:
          name: lockmypics-unlocker    
          path: ${{ github.workspace }}
