name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate Requirements
        uses: jfheinrich-eu/pipreqs-action@v4.4.2  # Use latest stable version
        with:
          PROJECT_PATH: "."
          REQUIREMENT_PATH: "requirements.txt"
          RECURSIVE: "true"
      - uses: actions/upload-artifact@master
        with:
          name: requirements  
          path: ${{ github.workspace }}/requirements.txt
